#server:
#  port: 8080
#
#spring:
#  datasource:
#    username: root
#    password: V(aWJBGuo0fa
#    url: jdbc:mysql://121.36.60.6:3306/doorscholar?useUnicode=true&characterEncoding=utf-8
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
##mybatis:
##  type-aliases-package: src/main/java/Entity
##  mapper-locations: classpath:Mapper/*.xml