#server:
#  port: 8080
#
#spring:
#  datasource:
#    username: root
#    password: V(aWJBGuo0fa
#    url: jdbc:mysql://localhost:3306/
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    hibernate:
#      ddl-auto: update
#
##mybatis:
##  type-aliases-package: src/main/java/Entity
##  mapper-locations: classpath:Mapper/*.xml